name: NodeSeek 自动签到评论加鸡腿

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # UTC 16:00，即北京时间 00:00
  workflow_dispatch: # Allow manual trigger

jobs:
  run-nodeseek-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Keeping original version as requested

      - name: Set up Python
        uses: actions/setup-python@v2 # Keeping original version as requested
        with:
          python-version: '3.11.8'

      # ========== START: MODIFICATION ==========
      # REMOVED the step "Install Chrome and Xvfb" which used apt-get

      # ADDED this step to correctly install matching Chrome and ChromeDriver
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable # Installs stable Chrome and matching ChromeDriver
      # ========== END: MODIFICATION ==========

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NodeSeek script
        env:
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          NS_RANDOM: ${{ secrets.NS_RANDOM }}
          HEADLESS: "true"
          # GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Make sure GEMINI_API_KEY is passed if your script uses it now
        run: |
          python nodeseek_daily.py # Assuming your script file is named nodeseek_daily.py
